In [3]:
import torch
torch.__version__

'2.7.1'

In [4]:
cuda_available = torch.cuda.is_available()
print(f"CUDA Available: {cuda_available}")
mps_available = torch.mps.is_available()
print(f"MPS Available: {mps_available}")
device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")
print(f"Using device: {device}")

CUDA Available: False
MPS Available: True
Using device: mps


In [5]:
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())

tensor(7)
0
7


In [6]:
vector = torch.tensor([1, 2, 3])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([1, 2, 3])
1
torch.Size([3])


In [7]:
matrix = torch.tensor([[1, 2],
                      [3, 4]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[1, 2],
        [3, 4]])
2
torch.Size([2, 2])


In [8]:
tensor = torch.tensor([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

print(tensor)
print(tensor.ndim)
print(tensor.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2
torch.Size([3, 3])


In [9]:
random_tensor = torch.rand(size=(3, 4))
print(random_tensor)
print(random_tensor.dtype)
print(tensor.shape)

tensor([[0.3124, 0.0300, 0.2429, 0.2942],
        [0.6538, 0.0181, 0.2614, 0.6643],
        [0.5378, 0.0158, 0.7268, 0.3264]])
torch.float32
torch.Size([3, 3])


In [10]:
zeros = torch.zeros(size=(2, 3))
print(zeros)
print(zeros.dtype)
ones = torch.ones(size=(2, 3))
print(ones)
print(ones.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [11]:
zero_ten = torch.arange(start=0, end=11, step=1)
print(zero_ten)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [12]:
tensor = torch.tensor([1, 2, 3])
tensor + 10
print(tensor)
print(tensor * 10)
tensor = tensor + 5
print(tensor)

tensor([1, 2, 3])
tensor([10, 20, 30])
tensor([6, 7, 8])


In [13]:
tensor = torch.tensor([1, 2, 3])
print(tensor * tensor)
print(torch.matmul(tensor, tensor))

tensor([1, 4, 9])
tensor(14)


In [14]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]], dtype=torch.float32)

print(tensor_A.shape)
print(tensor_B.shape)

torch.Size([3, 2])
torch.Size([3, 2])


In [15]:
tensor_C = torch.matmul(tensor_A, tensor_B.T)
print(tensor_C)
print(tensor_C.shape)

tensor([[ 23.,  29.,  35.],
        [ 53.,  67.,  81.],
        [ 83., 105., 127.]])
torch.Size([3, 3])


In [16]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [17]:
print(x.min())
print(x.max())
print(x.sum())
print(x.type(dtype=torch.float32).mean())

print(torch.argmax(x), torch.argmin(x))

tensor(0)
tensor(90)
tensor(450)
tensor(45.)
tensor(9) tensor(0)


In [18]:
x = torch.arange(1., 8.)
x.shape

torch.Size([7])

In [19]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [20]:
x_stacked = torch.stack([x, x], dim = 0)
y_stacked = torch.stack([x, x], dim = 1)
x_stacked, y_stacked

(tensor([[1., 2., 3., 4., 5., 6., 7.],
         [1., 2., 3., 4., 5., 6., 7.]]),
 tensor([[1., 1.],
         [2., 2.],
         [3., 3.],
         [4., 4.],
         [5., 5.],
         [6., 6.],
         [7., 7.]]))

In [21]:
x_squeezed = torch.squeeze(x_reshaped)
x_squeezed.shape


torch.Size([7])

In [22]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [23]:
print(x[0], x[0].shape)
print(x[0][0], x[0][0].shape)
print(x[0][0][0], x[0][0][0].shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) torch.Size([3, 3])
tensor([1, 2, 3]) torch.Size([3])
tensor(1) torch.Size([])


In [24]:
x[:, 0]

tensor([[1, 2, 3]])

In [25]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [26]:
x[:, 1, 1]

tensor([5])

In [27]:
x[0, 0, :]

tensor([1, 2, 3])

In [28]:
import numpy as np

In [29]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [30]:
tensor = torch.ones(7)
array = tensor.numpy()
tensor, array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# !nvidia-smi 
# For linux

zsh:1: command not found: nvidia-smi


In [32]:
device

device(type='mps')

In [33]:
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)
tensor_on_mps = tensor.to(device=device)
print(tensor_on_mps)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='mps:0')


In [34]:
tensor_on_mps.numpy()

TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [36]:
tensor_back_on_cpu = tensor_on_mps.cpu().numpy()
tensor_back_on_cpu, tensor_on_mps

(array([1, 2, 3]), tensor([1, 2, 3], device='mps:0'))